### ISSUE TITLE
[popup] Standardize the basic CSS for an element with the `popup` attribute

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#561]
Akin to the [`<dialog>` element's standardized styling](https://html.spec.whatwg.org/multipage/rendering.html#flow-content-3), I think it'd be helpful to authors to get a very basic set of standardized styles that the UA applies to pop-ups by default. Otherwise, `<div popup>Hello!</div>` is just the word "Hello", and isn't set apart from the page at all, which can be a bit confusing.

The default styles can be almost identical, I think, to the ones for dialog, perhaps only changing `position:absolute` to `position:fixed`:

```css
[popup="" i],
[popup=auto i],
[popup=hint i],
[popup=manual i] {
  position: fixed;
  inset-inline-start: 0;
  inset-inline-end: 0;
  width: fit-content;
  height: fit-content;
  margin: auto;
  border: solid;
  padding: 1em;
  background-color: Canvas;
  color: CanvasText;
}
```

It would seem to make sense for this UA rule to come before any rules that match specific elements, so that element-specific CSS overrides these.

Generally, thoughts? Objections?

**Comment by mfreed7** [comment]
Similarly, the fullscreen spec contains [this set of standard styles that apply to the ::backdrop pseudo element](https://fullscreen.spec.whatwg.org/#user-agent-level-style-sheet-defaults):

```css
::backdrop {
  position:fixed;
  top:0; right:0; bottom:0; left:0;
}

*|*:not(:root):fullscreen::backdrop {
  background:black;
} 
```

As written, and apparently as implemented in at least Chromium, the above CSS is used for both fullscreen elements **and** modal `<dialog>` elements.

For a pop-up element, I think the most common usage pattern would be to **not** style the `::backdrop`, because the pop-up isn't modal and doesn't want to obscure the page. But it seems helpful to at least include the sizing rules, and perhaps manage pointer events more carefully? How about this?

```css
[popup="" i]::backdrop,
[popup=auto i]::backdrop,
[popup=hint i]::backdrop,
[popup=manual i]::backdrop {
  position: fixed;
  top:0; right:0; bottom:0; left:0;
  background: transparent;
  pointer-events: none !important; /* So that clicks on the page can light-dismiss the pop-up */
}
```

**Comment by scottaohara** [comment]
I think the thing I'm most unsure of is the initial positioning. 
ideally these popups would be positioned based on their anchoring element, where applicable.  They wouldn't necessarily be fixed all the time?

Other question, so long as the attribute can be used on any element, i would expect some of these UA styles to be rather weak - e.g., the `hidden` attribute's `display: none`, to ensure that the base UA styles of a specific element (let's say `blockquote`) or other author styles take priority.  The latter not so much being a question as an expectation, but just trying to cover all the basis.

**Comment by mfreed7** [comment]
> I think the thing I'm most unsure of is the initial positioning. ideally these popups would be positioned based on their anchoring element, where applicable. They wouldn't necessarily be fixed all the time?

Hmm, interesting point. I think the problem is that technically you don't need to use the Anchor Positioning API to position a pop-up - you can put it top-left, or centered on the screen or whatever. I'm not sure what default style we'd apply that would "typically work" in the case that the pop-up has an `anchor` attribute. Perhaps a rule like:

```css
[popup][anchor] {
  top: anchor(bottom);
  left: anchor(left);
}
```

That feels odd to add to the standardized CSS though.


> 
> Other question, so long as the attribute can be used on any element, i would expect some of these UA styles to be rather weak - e.g., the `hidden` attribute's `display: none`, to ensure that the base UA styles of a specific element (let's say `blockquote`) or other author styles take priority. The latter not so much being a question as an expectation, but just trying to cover all the basis.

Totally agree - I'm not exactly sure how to specify that though. But that's what I meant by this sentence:
> It would seem to make sense for this UA rule to come before any rules that match specific elements, so that element-specific CSS overrides these.

**Comment by scottaohara** [comment]
yeh, thinking about it more, maybe if those anchoring styles were put in place (and if an rtl style where it was `right: anchor(right)` instead of `left`), then it would be on the author to do the rest.  that seems like the best reasonable default.

and sorry, don't know how that last sentence you had in there about UA style positions didn't register for me.

**Comment by mfreed7** [comment]
I think we likely also need to pull in a few more lines from the The [rendering section of the spec for `<dialog>`](https://html.spec.whatwg.org/multipage/rendering.html#rendering) under the "when its is modal flag is true" section, particularly these:

```css
  inset-block-start: 0;
  inset-block-end: 0;
  overflow: auto;
```

The `<dialog>` rendering section also includes these two rules, which seem like they must have some history. Not sure whether they should be ported to `<div popup>` or not:

```css
  max-width: calc(100% - 6px - 2em);
  max-height: calc(100% - 6px - 2em);
```

I'm sure @domenic knows where these come from and whether they are required here.

**Comment by tbondwilkinson** [comment]
For simplicity, I would remove border and padding from the default stylings and set background color to transparent. I can imagine most people overriding this.

I agree that you'd only want anchor positioning when you have an anchor element, but I'm not sure how you would style that from the UA.

**Comment by mfreed7** [comment]
> For simplicity, I would remove border and padding from the default stylings and set background color to transparent. I can imagine most people overriding this.

I just copied those nearly verbatim from [`<dialog>`'s styling](https://html.spec.whatwg.org/multipage/rendering.html#flow-content-3). The rationale, I imagine, was to set the `<dialog>` off from the page at least a little, by default. If you remove the border and make the background transparent, when you first start playing with `<div popup>Hello!</div>`, it can be confusing, since you can barely find the word "Hello!" overlaying other page content somewhere. Adding the padding/border/background makes it very easy. And as you point out, it's very easy to override.

@domenic do you know where the conversation took place about this styling for `<dialog>`? It'd be interesting to see how we arrived here.

**Comment by scottaohara** [comment]
While likely to be overwritten, being that this content should work in situations where author styles could be removed or revised (e.g., browser reader mode), I don't understand how it would be ok for the UA default style for an element whose purpose is to overlay other content of the page could have a transparent background.

**Comment by domenic** [comment]
> @domenic do you know where the conversation took place about this styling for `<dialog>`? It'd be interesting to see how we arrived here.

I can't find anything. In https://github.com/whatwg/html/commit/2fb24fcf3f916236e8767e2cb72b23e5c75b77e9 they arrived in the spec with full default styling. Various Google searches with `site:w3.org bugzilla` or `site:lists.whatwg.org` don't give any leads.

I personally like the idea of following the weak precedent provided by `<dialog>`. At least the background and border. I could be swayed to omit the padding.

**Comment by domenic** [comment]
Regarding `::backdrop` styling, I'm not sure many additional styles are necessary? You already get `position`, `top`, `right`, `bottom`, and `left` from the fullscreen spec's general `::backdrop`. `background` should default to `transparent`. So what's left is just adding `pointer-events: none !important;` for the popup cases.

**Comment by mfreed7** [comment]
@domenic thanks for digging, and too bad there's not much context. Also thanks for pointing out that the fullscreen spec already mandates most of the `::backdrop` styling. Chromium's implementation is individual per API, which is why I didn't even check.

If I keep the background/border because I heard several supportive comments, leave out the padding, and remove the overlap on `::backdrop` styling, here's what's left:

```css
[popup="" i],
[popup=auto i],
[popup=hint i],
[popup=manual i] {
  position: fixed;
  inset-inline-start: 0;
  inset-inline-end: 0;
  inset-block-start: 0;
  inset-block-end: 0;
  width: fit-content;
  height: fit-content;
  margin: auto;
  border: solid;
  overflow: auto;
  color: CanvasText;
  background-color: Canvas;
}

[popup="" i]::backdrop,
[popup=auto i]::backdrop,
[popup=hint i]::backdrop,
[popup=manual i]::backdrop {
    pointer-events: none !important;
}

[popup]:-internal-popup-hidden {
  display: none;
}
```

Objections?

**Comment by domenic** [comment]
> `[popup]:-internal-popup-hidden`

This seems bad?

**Comment by mfreed7** [comment]
> > `[popup]:-internal-popup-hidden`
> 
> This seems bad?

Sorry, in what sense? The behavior is bad? Or using an internal pseudo notation isn't the right way to express this in specs? (If the former, help me understand why it's bad? If the latter, what's the right way to specify this?)

**Comment by domenic** [comment]
I don't know what that's expressing, but I sure know that it's not something specs do. What is the goal of that Chromium-specific syntax? Then maybe we can talk about how to express it in specs.

**Comment by mfreed7** [comment]
> I don't know what that's expressing, but I sure know that it's not something specs do. What is the goal of that Chromium-specific syntax? Then maybe we can talk about how to express it in specs.

Ahh ok. So a `<div popup>` is `display:none` before it is shown. This rule makes that happen, via an internal CSS pseudo state (`:-internal-popup-hidden`) that matches when the pop-up shouldn't be showing. In [this section of the explainer](https://open-ui.org/components/popup.research.explainer#animation-of-pop-ups), step <span>#</span>1 of `.showPopUp()` is this:

> 1. Move the pop-up to the top layer, and **remove the UA display:none style**.

The CSS rule in question is how that is implemented. Suggestions appreciated (either here or on the upcoming spec PR, whichever you prefer) for how to write that in specs.

**Comment by mfreed7** [comment]
@emilio mentioned on https://github.com/openui/open-ui/issues/533 that the lack of `!important` on the `display:none` rule means that this CSS breaks things:

```css
[popup] {
  display: flex;
}
```

...because it overrides the UA rule that keeps non-showing pop-ups from being displayed.

The original purpose of **not** having `!important` on that rule was to make animations easier. But with https://github.com/openui/open-ui/issues/335 fixing those problems, I think we should probably add back `!important`.

**Comment by mfreed7** [comment]
Ok, with the resolution above plus the additional discussion, I think this is where we are:

```css
[popup] {
  position: fixed;
  inset-inline-start: 0;
  inset-inline-end: 0;
  inset-block-start: 0;
  inset-block-end: 0;
  width: fit-content;
  height: fit-content;
  margin: auto;
  border: solid;
  overflow: auto;
  color: CanvasText;
  background-color: Canvas;
}

[popup]::backdrop {
    pointer-events: none !important;
}

[popup]:{something that denotes the pop-up is in the hidden state} {
  display: none !important;
}
```

**Comment by mfreed7** [comment]
In my CL to implement the above changes, the reviewer called out the lack of `padding` explicitly. I don't disagree - having a border without padding looks odd to me:

<ins>with padding</ins>
<img width="129" alt="with_padding" src="https://user-images.githubusercontent.com/29559695/186000734-f0d425b7-da71-437d-8132-874fac850077.png">

<ins>no padding</ins>
<img width="125" alt="no_padding" src="https://user-images.githubusercontent.com/29559695/186000733-921ec35c-bbff-4696-9971-46c1ab029581.png">

Also, to point it out, `<dialog>` [has padding](https://html.spec.whatwg.org/multipage/rendering.html#flow-content-3):

<ins>dialog</ins>
<img width="101" alt="dialog" src="https://user-images.githubusercontent.com/29559695/186000730-f2f90555-a676-4b83-a9b9-1b47543ed4a9.png">

Are we sure we explicitly don't want to include padding in the default `popup` styles?

**Comment by dbaron** [comment]
For what it's worth, "the reviewer" was me.

I think the norm is that if a default style has `border`, then it should probably have `padding` as well, since a border with `0` padding looks pretty bad.

Given that popups are often smaller than dialogs, I'm not sure that the default for padding needs to be `1em`, though.  I think `0.25em` or `2px` would be plausible defaults as well.  (Table cells default to `1px`, even.)

**Comment by emilio** [comment]
Yeah some padding makes sense to me. I don't have a strong preference for how much. Half or quarter of an em probably makes sense (and it's probably sensible to make it em-based to be consistent with dialog, but...)

**Comment by tbondwilkinson** [comment]
I think I suggested leaving out the padding, but I meant it in the context of also leaving out the border because most people would probably override that style. People pointed out that we need the dialog to appear normal even if CSS doesn't load though, so I agree that if you have a border, some padding probably makes sense.

**Comment by mfreed7** [comment]
Thanks for the quick comments. Sounds like the start of consensus to make that change. While I'm here, I'll also point out this issue (https://github.com/whatwg/fullscreen/issues/201) because I think it makes sense to simplify the four `inset-*` properties into just `inset:0`. LMK if there are any disagreements with that.

Taken together, we're now here:

```css
[popup] {
  position: fixed;
  inset: 0;      /* Simplify to this */
  width: fit-content;
  height: fit-content;
  margin: auto;
  border: solid;
  padding: 0.25em;  /* Since I heard two people include 0.25em in their comments */
  overflow: auto;
  color: CanvasText;
  background-color: Canvas;
}

[popup]::backdrop {
    pointer-events: none !important;
}

[popup]:{something that denotes the pop-up is in the hidden state} {
  display: none !important;
}
```

Also for reference: 

<img width="170" alt="Screen Shot 2022-08-22 at 2 53 42 PM" src="https://user-images.githubusercontent.com/29559695/186025516-c73fc38c-9be2-450c-ac41-722a2665d254.png"> <img width="182" alt="Screen Shot 2022-08-22 at 2 54 05 PM" src="https://user-images.githubusercontent.com/29559695/186025513-fdcae294-5ef9-4549-a6fe-9daa82f9947f.png">

**Comment by scottaohara** [comment]
i personally like the .25em as a starting point.  but if people prefer the .5em, then that's absolutely fine as well.

**Comment by hidde** [comment]
Yay for default padding, 0.25em and 0.25em both look like a fine default to me.

**Comment by jh3y** [comment]
From someone who's spent a lot of time with `popup` recently, I don't think it makes sense to set `display: none !important` in the UA stylesheet 👎 

It's kinda restricting for use cases and scenarios that might pop up (no pun intended 😅)

You can still set a layout style inside the pop-up when it is in the top layer with

`[popup]:top-layer { display: flex; }`

But, a wrapper element within the `popup` also does the trick. I can think of and have been playing with scenarios where you could have a `popup` shown in the DOM by default and then promote it to the top layer. For example, think of pop out media like a video player that's in the normal document flow that you promote to top layer when playing. Or how you might do certain picture in picture mode. Especially with shared element transitions.

Also, PWA and app like components like sliding drawers etc. You might have a tab that you press or tap to promote an action sheet or drawer to the top layer. You then get the backdrop and light dismiss which is handy. We were playing with a concept like this the other day for native feel UI. I've also built things like this in the past which can be tricky when building app like experiences on the web.

I'm not saying that having `display: none` will be a bad thing. But, blocking any sort of escape hatch for it wouldn't be ideal. Otherwise we potentially block creative and advanced scenarios we might not have even thought of yet. 

The workaround as discussed with @mfreed7 would be to have some sort of JavaScript intervention that applies the `popup` attribute and calls `showPopUp` when necessary but seems rather OTT when before there was way out with only CSS and no JavaScript required.

**Comment by mfreed7** [comment]
Thanks for the additional votes for `0.25em`!


> From someone who's spent a lot of time with `popup` recently, I don't think it makes sense to set `display: none !important` in the UA stylesheet 👎

I just wanted to point out also that the `<dialog>` element does not have a similar `!important` rule. E.g.:

```html
<dialog>This will be visible!</dialog>
<style>dialog {display: flex;}</style>
```

Perhaps we should revisit that [hasty decision](https://github.com/openui/open-ui/issues/561#issuecomment-1220060058) on my part.

**Comment by tbondwilkinson** [comment]
I think `display: none;` is definitely a reasonable UA default, but I agree that `!important` feels a bit much.

FWIW, pop-out media players to me usually look modal in that they make the rest of the page non-interactible, see e.g. https://www.google.com/search?q=how+to+fish click on the video there, though this one completely hides the background you could imagine it graying the background instead. But since popups are intended to be modeless, those types of use cases aren't I think supported.

But I do think that people will be very tempted to use popup for things that they want to light dismiss, which may include taking parts of the DOM and showing them more prominently in the top-layer, or combining it with anchor positioning to move them out of their flow and attach to some other element.

**Comment by jh3y** [comment]
I don't think it would be so bad if we were able to override the UA styles, but, we can't.

The pop-out media idea was just one of those that came to mind. FWIW, I've definitely seen them light dismissable in the past where dismissing can even pause the content. You could achieve that behavior described with `popup=auto`.

Yeah, for me, it's impossible to think of every edge case or use case that might pop up. But, allowing people to show us would be ideal 👍

**Comment by gregwhitworth** [comment]
@mfreed7 I removed the agenda label for now since this was discussed in the past. Do you think you need to get another resolution given the changes?

**Comment by mfreed7** [comment]
> I wonder why there is no selector for the "is hidden" state? If the UA wants to style it, isn't it possible the user might as well?

Yeah, I was thinking it might be useful to have something like `:popup-opening`, which matches pop-ups that aren't in the hidden state. Then you could style the transitioning-open state separately from the fully-`:open` state. I'm still not clear what the use case is for that, but I've heard it requested.

The alternative is `:popup-hidden`, but that seems a bit more difficult to use for styling transitions, since you'd need to always use `:not(:popup-hidden)` for that. But maybe the real use case is styling pop-ups in the page when they're not officially showing. E.g. a small visible element that, when clicked, gets bigger and becomes a pop-up. I've also heard about that use case.

We need to better-understand the use cases, I think, in order to get the right polarity and name for this pseudo.

**Comment by tbondwilkinson** [comment]
I think [an :open](https://github.com/w3c/csswg-drafts/issues/7319#issuecomment-1225988203) pseudoclass kind of implies the possibility for a `:closed`? That feels like what Domenic might be asking. I think `:opening` and `:closing` are useful additional states, where something could be still marked as `:closed` but also as `:opening` for styling transitions, perhaps.

**Comment by mfreed7** [comment]
> I think [an :open](https://github.com/w3c/csswg-drafts/issues/7319#issuecomment-1225988203) pseudoclass kind of implies the possibility for a `:closed`? That feels like what Domenic might be asking. I think `:opening` and `:closing` are useful additional states, where something could be still marked as `:closed` but also as `:opening` for styling transitions, perhaps.

Ahh, you might be right that `:closed` was what @domenic was requesting? I always wonder whether we really should add negated pseudo classes for everything, when we have `:not()`. But here, this is interesting, because the "open" state for a pop-up is actually tri-state (hidden, transitioning, and showing). So there is an unobservable state unless we add a specific pseudo for it. Hence the `:opening` (or `:opening-or-open`?) suggestion.

**Comment by tbondwilkinson** [comment]
True, `:not(:open)` could be the thing that you specify here for `display: none;` for now?

I hadn't considered the option of a tri-state... or would it be a quad state so you could style transitioning to open and transitioning to close separately? I think people could probably argue for a while about whether to considering something that is "opening" "open" or "closed" so it might be good at least to consider side-stepping that argument by considering that a separate state. I do think people will fall into various categories:

1. Consider open/close to be a binary. Either a popup is open or its not.
2. Consider open/close to have additional edge states for opening and closing. And whether they considering opening/closing to fall under open or close may vary.

**Comment by mfreed7** [comment]
> True, `:not(:open)` could be the thing that you specify here for `display: none;` for now?

Can't do that - `:open` means the pop-up is in the "showing" state. So `:not(:open)` would mean *either* "hidden" or "transitioning", and we definitely only want to apply `display:none` when "hidden". Else transitions are broken.


> I hadn't considered the option of a tri-state... or would it be a quad state so you could style transitioning to open and transitioning to close separately? I think people could probably argue for a while about whether to considering something that is "opening" "open" or "closed" so it might be good at least to consider side-stepping that argument by considering that a separate state. I do think people will fall into various categories:
> 
> 1. Consider open/close to be a binary. Either a popup is open or its not.
> 2. Consider open/close to have additional edge states for opening and closing. And whether they considering opening/closing to fall under open or close may vary.

Ugh. This is why I hesitated to specify an explicit pseudo state for this. Perhaps this part of the feature needs more discussion before we introduce it. Certainly I don't think it is needed for "v1".

---

Last call for objections to this being the proposed standard CSS for `popup`:

```css
[popup] {
  position: fixed;
  inset: 0;
  width: fit-content;
  height: fit-content;
  margin: auto;
  border: solid;
  padding: 0.25em;
  overflow: auto;
  color: CanvasText;
  background-color: Canvas;
}

[popup]::backdrop {
    pointer-events: none !important;
}

[popup]:{spec language for "is hidden"} {
  display: none;
}
```
