### ISSUE TITLE
Link `focus` and `hover` should follow WAI-ARIA WCAG AA guidelines

### ISSUE THREAD

**Issue by summercms** [openui/open-ui#658]
Not sure if this is something this repo can use, but decided to open an issue.

### Code Example 1

```css
a {
    color: #2AB1E3;
}
a:focus, a:hover {
    color: #1892BF;
}
```

Gives the following result:

![image](https://user-images.githubusercontent.com/57409060/215775259-65136fa2-26dc-402d-a5e8-161621b88bfc.png)

The above makes it hard to tell if the website is confirming you are **hovering** over a link with bad eye sight.

### Code Example 2

```css
a {
    color: #2AB1E3;
}
a:focus, a:hover {
    color: #083644;
}
```

Gives the following result:

![image](https://user-images.githubusercontent.com/57409060/215775695-9a5c1892-fa8e-4c2e-8955-801fbf3038d3.png)

The above makes it obvious the website is confirming you are **hovering** over a link with poor eye sight.

### W3c Spec

Did a search and can find info on `focus` ring. But no mention above `hover`

Link: https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/#2411-focus-appearance-aa
