### ISSUE TITLE
[popover] Entry/Exit animations don't work as explained

### ISSUE THREAD

**Issue by jh3y** [openui/open-ui#718]
Hey y'all!

Showing some of these APIs next week and it seems the `display` transition stuff isn't quite there yet?

My understanding is that this _should_ work? (After messing about with the syntax and digging around to find examples scattered about).

```css
[popover] {
  opacity: var(--showing, 0);
  transition: opacity 0.5s, display 0.5s, overlay 0.5s;
}

[popover]:initial {
  --showing: 0;
}

[popover]:popover-open {
  --showing: 1;
}
```

But, with this code, only the "Exit" animations are honored and the entry ones aren't. cc @mfreed7 @josepharhar 

See it in action [here](https://codepen.io/jh3y/pen/rNqOLwe/094fef81a39ba4a17f1abdaa415315ae)

– Jhey

**Comment by josepharhar** [comment]
You should use `@initial` and combine it with `:popover-open` like this instead of using `:initial`:
```css
[popover]:popover-open {
  @initial {
    --showing: 0;
  }
  --showing: 1;
}
```

Here is a fixed codepen that is working on my machine: https://codepen.io/jarhar/pen/BaqozGe
