### ISSUE TITLE
selectlist: Animating changes in the selected value

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#824]
I was talking to @argyleink about how the `<selectedoption>` element sets new values in https://github.com/openui/open-ui/issues/571#issuecomment-1696637459 and he was interested in whether the author could create a transition or a view transition when the `<selectedoption>` content changes. Maybe this is something we could find a way to support?

**Comment by argyleink** [comment]
UA styles are like:

```css
.color-picker selectedoption {
  view-transition-name: none;
}
```

But author styles are like, no way, lemme animate:

```css
selectedoption {
  view-transition-name: selected-color-option;
}

::view-transition-new(selected-color-option) {
  animation: var(--slide-in-up);
}

::view-transition-old(selected-color-option) {
  animation: var(--slide-out-up);
}
```
