### ISSUE TITLE
selectlist: customizing the default button's marker is weird

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#881]
I was just trying to change the color of the marker in the selectlist's default button, which can be accessed via `::marker` - although I haven't implemented this in the chromium prototype yet, so for now its still `::part(marker)`.

Setting `color` or `content` didn't seem to do anything. I even removed the `background-image` property to get rid of the svg that we currently render in there, but that didn't make the `content` start showing...

This would have been easier to do when we had a slot for the marker to replace it with whatever you want, but if you really want to customize the default marker then you're better of just using your own `<button type=selectlist>`.

Should we encourage people to make their own `<button type=selectlist>` in order to customize the marker and consider getting rid of `::marker` entirely if it isn't useful? Or should we make `::marker` easier to use, perhaps by changing the user-agent styles? I don't feel like it's important enough to make a new `<marker>` element to bring us up to par with the slot we used to have, but maybe it is...

Here are the styles that we currently have in the marker in the chromium prototype:
```css
selectlist::-internal-selectlist-button-icon {
    background-image: -internal-light-dark(url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMTQiIHZpZXdCb3g9IjAgMCAyMCAxNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj5cCiAgPHBhdGggZD0iTTQgNiBMMTAgMTIgTCAxNiA2IiBzdHJva2U9IldpbmRvd1RleHQiIHN0cm9rZS13aWR0aD0iMyIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPlwKPC9zdmc+), url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMTQiIHZpZXdCb3g9IjAgMCAyMCAxNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj5cCiAgPHBhdGggZD0iTTQgNiBMMTAgMTIgTCAxNiA2IiBzdHJva2U9IiNmZmZmZmYiIHN0cm9rZS13aWR0aD0iMyIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPlwKPC9zdmc+));
    background-origin: content-box;
    background-size: contain;
    height: 1em;
    margin-inline-start: 4px;
    opacity: 1;
    padding-bottom: 2px;
    padding-inline-start: 3px;
    padding-inline-end: 3px;
    padding-top: 2px;
    width: 1.2em;
    min-width: 1.2em;
    max-width: 1.2em;
    background-repeat: no-repeat;
    outline: none;
}
```

**Comment by lukewarlow** [comment]
https://github.com/openui/open-ui/issues/863#issuecomment-1760226526 could it be due to the property limitations mentioned here? Or I guess if it's not using the pseudo element potentially not?

**Comment by scottaohara** [comment]
Is a marker element a way to solve this and the “checkmark” in the option element like we were talking about today?

something the browser renders if someone doesn’t add it (like the summary element in a details) but if someone does add it, the browser skips adding it and uses that instead?

If this is  a bad idea, please disregard

**Comment by lukewarlow** [comment]
Hmm that's an interesting idea. Could apply the default hide this from accessibility tree behaviour. Would it require an SVG / img (well I guess anything) child or if you just included it on its own would it still use the default Glyph? Could that allow you to position it without needing your own SVG?

**Comment by josepharhar** [comment]
> could it be due to the property limitations mentioned here?

No, considering that its still `::part(marker)` that I'm using in the prototype.

> something the browser renders if someone doesn’t add it (like the summary element in a details) but if someone does add it, the browser skips adding it and uses that instead?

I wanted to just change the color of it at first in which case I didn't want the browser to skip adding stuff, but in the case that I added `content` I did want the browser to skip adding it. I'm not sure exactly how this stuff would be implemented.

**Comment by josepharhar** [comment]
> Should we encourage people to make their own `<button type=selectlist>` in order to customize the marker and consider getting rid of `::marker` entirely if it isn't useful?

The more I think about it, the more appealing this sounds to me. I'd like to propose that we remove `::marker` because imo it isn't very useful.

**Comment by scottaohara** [comment]
is there really no use case for this element to _not_ be customized?  i still see enough instances of rudimentary forms being implemented for internal use, where designers aren't assigned to projects and devs just use standard HTML elements without needing to gussy them up.   I don't think it's a good idea to simply do away with the marker for default UA rendering, unless it's replaced with some other means of providing a default UA style for the chevron.

**Comment by lukewarlow** [comment]
I think the intention was to remove the marker pseudo but not to remove the default marker right? So the default UI would still look like currently?

**Comment by josepharhar** [comment]
I am planning on experimenting with replacing the svg data url with an actual svg element in the user agent shadowroot to see if that it more stylable.

**Comment by josepharhar** [comment]
I threw together a [work in progress patch](https://chromium-review.googlesource.com/c/chromium/src/+/5514970) to add checkmarks next to selected options by adding this to the UA stylesheet:
```css
select option::before {
  content: '';
  display: inline-block;
  inline-size: 1.4em;
  block-size: 1.0em;
  background-image: url(data:image/svg+xml,%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22m8.229%2014.062-3.521-3.541L5.75%209.479l2.479%202.459%206.021-6L15.292%207l-7.063%207.062Z%22%20fill%3D%22%23000%22%2F%3E%3C%2Fsvg%3E);
  background-origin: content-box;
  background-repeat: no-repeat;
  background-size: cover;
}
select option:not(:checked)::before {
  visibility: hidden;
}
```
Here is a screenshot of what it looks like:
![Screenshot 2024-05-03 at 9 38 47 AM](https://github.com/openui/open-ui/assets/7681467/dba6fe56-5cad-40db-8d3f-852a6162bf4c)
You can opt-out of it with `option::before { display:none; }`.


I feel like using `::before` won't make it through the standards and maybe we would have to switch to `::marker` or create a new pseudo-element, but is this what yall would like? Would having this by default get in the way of anything? Are there any improvements to the style rules I wrote that yall can think of?
