### ISSUE TITLE
[Invokers] What about de-hover/de-focus?

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#905]
In my original [popover hover-triggering explainer](https://open-ui.org/components/popover-hint.research.explainer/#css-values-to-control-delay), and in the [CSSWG discussion](https://github.com/w3c/csswg-drafts/issues/9236), there are actually **two** hover/focus related triggers:
 - hover or focus to **show** a popover
 - de-hover or de-focus to **hide** a popover

Is the second behavior considered in this proposal? Should it be? Perhaps that's just a separate feature that relates only to popovers? I ask because you've very creatively weaved this proposal into a nice, general thing for all kinds of features, not just popovers. Perhaps you can work the same magic for the de-hover case?

**Comment by keithamus** [comment]
If I'm understanding the question, I think this is covered by the `loseinterest` event.

**Comment by mfreed7** [comment]
> If I'm understanding the question, I think this is covered by the `loseinterest` event.

You are of course correct. I forgot about that part of the proposal, and my quick search failed to find it. I think that sounds like a reasonable way to do things. It has a few differences as compared to my popover-specific proposal:
 1. You can only `loseinterest` if you had an `interest` in the first place. I.e. you can't have a popover that goes away if not hovered for some time, but never got hover-triggered in the first place. I'll admit that's *very* corner case, so this is probably fine.
 2. There isn't a way to control the delays, either for showing interested or losing interest. I *do* think that level of control might be important for developers. A common complaint, for example, about the browser-native tooltip functionality (via the `title` attribute) is that the hover-delay is too long. And the delay is even more important on the de-hover side of things. Some people want a quick de-hover and others want a long one.

Have you thought about <span>#</span>2? Did I just miss it also in the explainer? (I did a better search this time, I think.)

**Comment by keithamus** [comment]
Regarding 1; can you expand on this please? I'm not fully sure I understand. Do you mean if the popover is first opened programmatically, or is the use-case around multiple input modalities?


Regarding 2; I agree control is useful and specifying it in CSS seems right to me (modulo a11y concerns?). 

I wonder if there is a general purpose solution to this though, as I suggested in https://github.com/openui/open-ui/issues/781 and subsequently https://github.com/w3c/csswg-drafts/issues/9062. A few of us (including Tab) discussed this at TPAC (after-hours), and I got the sense that there's a few ideas we could try, we just need to come up with something tenable. My ideas (which may be terrible) are: 

 - Having a psuedo class applied explicitly to elements that we want to allow a transition like this on (`dialog`, `details`, `[popover]`), and having those classes applied for the duration of the animation that is applied to them.

```css
:is([popover], dialog, details):showing {
  animation: fade-in 200ms;
  animation-delay: 2s; /* :showing will last as long as this (getcomputedstyle?) */
}
:is([popover], dialog, details):hiding {
  animation: fade-out 200ms;
  animation-delay: 2s; /* :hiding will last as long as this (getcomputedstyle?) */
}
```

 - Having some kind of state transition combinator that lets you cue up animations between a selector that is about to traverse to another selector, allowing for discrete animations _between_ states e.g.:

```css
dialog -> dialog[open] {
  animation: fade-in 200ms;
}
dialog[open] -> dialog:not([open]) {
  animation: fade-out 200ms;
}
```

 - Defining explicit rules for elements that are applied while elements switch out of  `display:none`:

```css
@entry {
  [popover] {
    opacity: 0;
  }
}

[popover] {
  display: block;
  transition: opacity 0.2s display 0.2s;
}
```
