### ISSUE TITLE
[Invokers] no magic defaults please

### ISSUE THREAD

**Issue by tomByrer** [openui/open-ui#906]
```html
<button invoketarget="my-video">Play/Pause</button>
```

I do not think there should be magic defaults like this.  Could be mis-labeled & bad for ARIA, etc.
I'll grab the attention of others in the Video Player field to chime in, but for now I'd like to see:
```html
<button invoketarget="my-video" invokeaction="playpause">Play/Pause</button>
```
& then one can CSS:
```css
button[invokeaction="playpause"] {
  background-color: gold;
}
```

Otherwise, great proposal!

**Comment by keithamus** [comment]
I disagree and I think the defaults are an ergonomic win. Less so for video, perhaps, but certainly for dialogs and popovers, where 99% of the time folks are going to want the button to do the intuitive thing (toggle the visibility of the UI).

>  Could be mis-labeled & bad for ARIA, etc.

Could you please expand on what you see is the problem here? The _intent_ behind the proposal is to allow the browser to handle more of the ARIA stuff on your behalf. 

> CSS

You can still have the "magic default" with slightly more CSS:

```css
button:is(:not([invokeaction], [invokeaction=auto i]),  {
  background-color: gold;
}
```
